name: Docker Build Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_base_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Get changed files
        id: changed-files-yaml
        uses: tj-actions/changed-files@v37
        with:
          files_yaml: |
            doc:
              - Gemfile
      - name: Build Docker Base Image
        if: steps.changed-files-yaml.outputs.doc_any_changed == 'true'  
        run: docker build -t myapp-base -f Dockerfile.base .

  build_code_image:
    runs-on: ubuntu-latest
    needs: build_base_image
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Code Image
        if: ${{ github.event_name == 'push' && github.event_path != 'Gemfile' }}
        run: docker build -t myapp-code -f Dockerfile.runner .
