name: Docker Build Pipeline

on:
  push:
    branches: [ "main" ]
    paths:
      - Gemfile
      - Gemfile.lock
  pull_request:
    paths:
      - Gemfile
      - Gemfile.lock
      - '**/*.rb'   # Modify this to match the file extension of your code files
  workflow_dispatch:

jobs:
  build_base_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Base Image
        if: github.event_name == 'push' && github.event_path == 'Gemfile'
        run: docker build -t myapp-base -f Dockerfile.base .

  build_code_image:
    runs-on: ubuntu-latest
    needs: build_base_image
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Code Image
        if: github.event_name == 'push' && github.event_path != 'Gemfile'
        run: docker build -t myapp-code -f Dockerfile.runner .
